apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "etcd.fullname" . }}-metrics
  labels:
    app.kubernetes.io/component: metrics
    {{- include "etcd.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.metrics.serviceMonitor.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{ range .Files.Lines "prometheus-mixin/rules.yaml" }}{{ . | nindent 2 }}{{- end }}
