apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.peerPort }}
      targetPort: peer
      protocol: TCP
      name: etcd-server
    - port: {{ .Values.service.clientPort }}
      targetPort: client
      protocol: TCP
      name: etcd-client
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
