apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "busybox.fullname" . }}
  labels:
    {{- include "busybox.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "busybox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "busybox.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "busybox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          command:
            - /app/busybox
          args:
            - --listen-addr
            - :{{ .Values.service.port }}
            {{- if .Values.logJson }}
            - --log-json
            - {{ .Values.logJson }}
            {{- end }}
            {{- if .Values.logStacktrace }}
            - --log-stacktrace
            - {{ .Values.logStacktrace }}
            {{- end }}
          {{- if .Values.extraEnvs }}
          env:
            {{- if .Values.metrics.jaegerAddr }}
            - name: JAEGER_TRACE
              value: {{ .Values.metrics.jaegerAddr }}
            {{- end }}
            {{ toYaml .Values.extraEnvs | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe}}
          readinessProbe:
            {{ toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{ toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- with .Values.extraVolumeMounts}}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
