apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}-metrics
  labels:
    app.kubernetes.io/component: metrics
    {{- include "etcd.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports:
    - port: 8081
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
